export const initialData = [
  {id: 1,  lat: 34.06, long: -84.67, pressure: null, cityName: 'Acworth', humidity: null, temperature: null},
  {id: 2,  lat: 34.37, long: -84.92, pressure: null, cityName: 'Adairsville', humidity: null, temperature: null },
  {id: 3,  lat: 31.13, long: -83.43, pressure: null, cityName: 'Adel', humidity: null, temperature: null },
  {id: 4,  lat: 32.53, long: -82.59, pressure: null, cityName: 'Adrian', humidity: null, temperature: null },
  {id: 5,  lat: 32.19, long: -82.57, pressure: null, cityName: 'Ailey', humidity: null, temperature: null },
  {id: 6,  lat: 32.15, long: -82.78, pressure: null, cityName: 'Alamo', humidity: null, temperature: null },
  {id: 7,  lat: 31.38, long: -83.22, pressure: null, cityName: 'Alapaha', humidity: null, temperature: null },
  {id: 8,  lat: 31.58, long: -84.18, pressure: null, cityName: 'Albany', humidity: null, temperature: null},
  {id: 9,  lat: 33.05, long: -84.18, pressure: null, cityName: 'Aldora', humidity: null, temperature: null },
  {id: 10, lat: 31.78, long: -81.61,  pressure: null, cityName: 'Allenhurst', humidity: null, temperature: null },
  {id: 11, lat: 32.59, long: -83.23,  pressure: null, cityName: 'Allentown', humidity: null, temperature: null },
  {id: 12, lat: 31.54, long: -82.47,  pressure: null, cityName: 'Alma', humidity: null, temperature: null },
  {id: 13, lat: 34.07, long: -84.27,  pressure: null, cityName: 'Alpharetta', humidity: null, temperature: null },
  {id: 14, lat: 32.08, long: -82.48,  pressure: null, cityName: 'Alston', humidity: null, temperature: null },
  {id: 15, lat: 34.47, long: -83.57,  pressure: null, cityName: 'Alto', humidity: null, temperature: null },
  {id: 16, lat: 31.59, long: -83.01,  pressure: null, cityName: 'Ambrose', humidity: null, temperature: null },
  {id: 17, lat: 32.07, long: -84.22,  pressure: null, cityName: 'Americus', humidity: null, temperature: null },
  {id: 18, lat: 32.2, long: -84.15, pressure: null, cityName: 'Andersonville', humidity: null, temperature: null },
  {id: 19, lat: 31.83, long: -83.73, pressure: null, cityName: 'Arabi', humidity: null, temperature: null },
  {id: 20, lat: 34.05, long: -85.06, pressure: null, cityName: 'Aragon', humidity: null, temperature: null },
]